# Lovelace-UI file for Home Assistant, Settings view
# Type: Home Assistant yaml file
# Date: 12-07-2019
# Author: R.Bisschops
#
# Changelog:
# V0.1.0:  First version
# V0.2.0:  Removed lighting settings (moved to lighting tab)
# V0.3.0:  Added Zigbee2mqtt settings
# V0.4.0:  Changed some configs
# V0.4.1:  Changed UI layout
# V0.5.0:  Changed layout of wifi and gps home buttons due to change of owntracks location  in HA 0.95

title: Settings
icon: 'mdi:settings'
cards:
  - type: vertical-stack
    cards:
    - type: entities
      show_state: false
      show_name: false
      show_header_toggle: false
      title: Instellingen
      entities:
      - type: section
      - entity: input_boolean.text_notifications
        name: Tekst notificaties
        icon: 'mdi:bell'
      - entity: input_boolean.holiday_mode 
        name: Vakantie mode
        icon: 'mdi:briefcase'
      - entity: input_boolean.recording_mode
        name: Recorder mode
        icon: 'mdi:video'

  - type: vertical-stack
    cards:
    - type: entities
      show_state: false
      show_name: false
      show_header_toggle: false
      title: Automatiseringen
      entities:
      - type: section      
      - entity: automation.buitenlamp_bij_thuiskomst
        name: Buitenlamp bij thuiskomst
      - entity: automation.er_komt_iemand_thuis
        name: Er komt iemand thuis
      - entity: automation.iedereen_is_weg  
        name: Iedereen is weg
      - entity: automation.tuinverlichting_bij_thuiskomst
        name: Tuinverlichting aan bij thuiskomst
      - entity: automation.tuinverlichting_bij_zonsondergang 
        name: Tuinverlichting aan bij zonsondergang
      - entity: automation.toilet_verwarming_aan_volgens_schema_niet_werkdagen
        name: Toilet verwarming aan volgens schema - niet werkdagen
      - entity: automation.toilet_verwarming_aan_volgens_schema_werkdagen
        name: Toilet verwarming aan volgens schema - werkdagen

  - type: vertical-stack
    cards:
    - type: entities
      show_state: false
      show_name: false
      show_header_toggle: false
      title: Zigbee2mqtt instellingen
      entities: 
      - type: section      
      - entity: input_select.zigbee2mqtt_log_level
        name: Zigbee2mqtt log level 
      - entity: input_boolean.zigbee_permit_join
        name: Zigbee2mqtt permit join
      - entity: timer.zigbee_permit_join
        name: Resterende join tijd


