# Lovelace-UI file for Home Assistant
# Type: Home Assistant yaml file
# Date: 01-02-2019
# Author: R.Bisschops
#
# Changelog:
# V0.1.0:  First version
# V0.2.0:  Added Utilities view

resources:
  - url: /local/custom_cards/mini-graph-card-bundle.js?v=0.3.0
    type: module
  - url: /local/custom_cards/button-card.js?v=0.0.6 
    type: module

title: Bisschops Mansion
background: center / cover no-repeat url("/local/background2.jpg") fixed
views:
  - !include lovelace/groundfloor.yaml
  - !include lovelace/firstfloor.yaml
  - !include lovelace/secondfloor.yaml
  - !include lovelace/garden.yaml
  - !include lovelace/lighting.yaml
  - !include lovelace/mediaplayer.yaml
  - !include lovelace/weather.yaml
  - !include lovelace/utilities.yaml
  - !include lovelace/stats.yaml
  - !include lovelace/settings.yaml
  - !include lovelace/test.yaml