# Device trackers configuration file for Home Assistant  
# Type: Home Assistant yaml file
# Date: 04-04-2018
# Author: R.Bisschops
#
# Changelog:
# V0.1.0:  First version
#
#- platform: nmap_tracker
#  hosts: 
#    - !secret ip_harmony_hub
#    - !secret -Pn ip_nmap_hosts
#    - !secret ip_nmap_hosts
#    - !secret ip_voip
#    - !secret ip_fax
#    - !secret ip_nas_1
#    - !secret ip_nas_2
#    - !secret ip_hp_printer
#    - !secret ip_domoticz_master
#    - !secret ip_ha_bridge
#    - !secret ip_mysensors
#    - !secret ip_domoticz_slave
#    - !secret ip_hue_bridge
#    - !secret ip_echo_dot
#    - !secret ip_homeassistant
#    - !secret ip_xiaomi_aquara
#  home_interval: 10
#  exclude: 
#    - !secret ip_homeserver
#    - !secret ip_netgear

# - platform: owntracks
#  max_gps_accuracy: 200

- platform: netgear
  host: !secret ip_netgear
  password: !secret netgear_password
  exclude: 
    - !secret mac_ubiquiti_ap_1
    - !secret mac_homeserver


