## Package file for Home Assistant, used for setting the Hue scenes  
## Type: Home Assistant yaml file
## Date: 11-11-2019
## Author: R.Bisschops
##
## Changelog:
## V0.1.0:  First version
## V0.1.1:  Minor comments updates
## V0.1.2:  Update group name
## V0.1.3:  Removed Verlichting uit as its not a real Hue scene 
## V0.2.0:  Major update for HA 
## V1.0.0:  Production version 1.0.0
## V1.1.0:  Added group living_room_hue_lights (from groups) 
## V1.1.1:  Cleanup code
## V1.2.0:  Added scrips for controlling hue lamps direct (without using scenes)
## V1.3.0:  Moved in input select for hue modes (from package_livingroom)

## Notes: Scenes are stored in the Hue Bridge and can be
## edited with the Hue V1 and/or V2 App

###############################################################################
##  Homeassistant settings
###############################################################################

homeassistant:
  customize:
    script.set_hue_scene:
      icon: mdi:lightbulb

## Hue bridges and emulators
hue:
  bridges:
    - host: !secret ip_hue_bridge
      filename: phue_bridge.conf
      allow_unreachable: true
      allow_hue_groups: true
#    - host: !secret ip_ha_bridge
#      filename: phue_emulator.conf
#      allow_unreachable: true

###############################################################################
##  Entities
###############################################################################

## Input selectors for scenes and Rooms
input_select:
  hue_scenes:
    name: Licht scenes woonkamer
    icon: mdi:lightbulb
    options:
      - Concentratie
      - Energie
      - Gedimd
      - Helder 
      - Lezen
      - Nachtlampje
      - Ontspannen
      - Schoonmaken
      - TV mode
      - Verlichting aan
      - Zonsondergang
    initial: Verlichting aan
  hue_groups:
    name: Ruimte
    icon: mdi:group
    options:
      - Woonkamer
      - Keuken
    initial: Woonkamer
  ## Mode selector for the lights in the livingroom
  ## used for the modes the light can be set in from media center
  livingroom_lights_mode:
    name: Verlichtsmode Woonkamer
    options:
      - Normaal
      - Video
    initial: Normaal
    icon: mdi:lightbulb

###############################################################################
##  Groups
###############################################################################

## Group with the Scenes, Rooms and script, used in the UI
group:
  hue_light_control:
    name: Verlichting
    icon: mdi:spotlight
    entities:
      - light.woonkamer
      - input_select.hue_scenes
      - input_select.hue_groups
      - script.set_hue_scene
  living_room_hue_lights_all:
    name: Verlichting woonkamer
    entities:
      - light.lage_kast_links
      - light.lage_kast_rechts
      - light.staande_lamp_links
      - light.staande_lamp_rechts
  ## Added V1.2.0
  living_room_hue_lights_low_cabinets:
    name: Verlichting lage kasten
    entities:
      - light.lage_kast_links
      - light.lage_kast_rechts
  ## Added V1.2.0
  living_room_hue_lights_standing_lamps:
    name: Verlichting staande lampen
    entities:
      - light.staande_lamp_links
      - light.staande_lamp_rechts
###############################################################################
##  Automations
###############################################################################


###############################################################################
##  Templates
###############################################################################


###############################################################################
##  Scripts
###############################################################################

script:
  ## Script for setting the Hue scene manual
  manual_set_hue_scene:
    alias: Set Hue scenes handmatig
    sequence: 
      - service: script.set_hue_scene
        data_template:
          group: '{{ states.input_select.hue_groups.state }}'
          name: '{{ states.input_select.hue_scenes.state }}'

  ## Script for setting the Hue scene manual
  ## used by multiple packages (media_center)
  set_hue_scene:
    alias: Send Hue scene naar Hue Bridge
    sequence: 
      - service: hue.hue_activate_scene
        data_template:
          group_name: '{{ group }}'
          scene_name: '{{ name }}'

  ## Added V1.2.0
  ## Script for setting Hue lamps in video mode
  ## used in package_media_center
  # hue_mode_video:
  #   alias: Licht aanpassen voor video mode
  #   sequence:
  #     - service: light.turn_on
  #       data_template:
  #         entity_id: group.living_room_hue_lights_low_cabinets
  #         brightness: 90
  #         xy_color: [0.502, 0.414]
  #         transition: 5
  #     - service: light.turn_on
  #       data_template:
  #         entity_id:  group.living_room_hue_lights_standing_lamps
  #         brightness: 100
  #         xy_color: [0.502, 0.414]
  #         transition: 5

# [0.502, 0.414] releax
# [0.459, 0.411] normal

  ## Added V1.2.0
  ## Script for setting Hue lamps in normal mode
  ## used in package_media_center
  # hue_mode_normal:
  #   alias: Licht aanpassen voor normal mode
  #   sequence:
  #     - service: light.turn_on
  #       data_template:
  #         entity_id: group.living_room_hue_lights_low_cabinets
  #         brightness: 100
  #         xy_color: [0.502, 0.414]
  #         transition: 5
  #     - service: light.turn_on
  #       data_template:
  #         entity_id: group.living_room_hue_lights_standing_lamps
  #         brightness: 150
  #         xy_color: [0.502, 0.414]
  #         transition: 5

  ## Added V1.2.0
  ## Script for setting Hue lamps in video or normal mode
  ## used in package_media_center
  hue_mode_change:
    alias: Licht aanpassen voor video of normale mode
    sequence:
      - service: script.set_hue_scene_auto
        data_template:
          brightness_stop_group_1: >
            {% if (states.input_select.livingroom_lights_mode.state == "Video") %}
              90
            {% else %}
              100
            {% endif %}
          brightness_stop_group_2: >
            {% if (states.input_select.livingroom_lights_mode.state == "Video") %}
              100
            {% else %}
              150
            {% endif %}
          profile_stop_1: >
            {% if (states.input_boolean.christmas_mode.state == "on") %}
              "christmas_normal_1"
            {% else %}
              "normal_1"
            {% endif %}
          profile_stop_2: >
            {% if (states.input_boolean.christmas_mode.state == "on") %}
              "christmas_normal_2"
            {% else %}
              "normal_2"
            {% endif %}
          transition: 5

  ## Added V1.2.0
  ## Script for setting Hue lamps in relax mode
  # hue_mode_relax:
  #   alias: Licht aanpassen voor relax mode
  #   sequence:
  #     - service: light.turn_on
  #       data_template:
  #         entity_id: group.living_room_hue_lights_low_cabinets
  #         brightness: 100
  #         xy_color: [0.502, 0.414]
  #         transition: 5
  #     - service: light.turn_on
  #       data_template:
  #         entity_id: group.living_room_hue_lights_standing_lamps
  #         brightness: 150
  #         xy_color: [0.502, 0.414]
  #         transition: 5

  ## Added V1.2.0
  ## Script for setting Hue lamps at sunset
  ## used in package_livingroom
  # hue_sunset_mode:
  #   alias: Licht aan bij zonsondergang
  #   sequence:
  #     - service: light.turn_on
  #       data_template:
  #         entity_id: group.living_room_hue_lights_all
  #         brightness: 1
  #         xy_color: [0.459, 0.411]
  #     - delay:
  #           seconds: 1
  #     - service: light.turn_on
  #       data_template:
  #         entity_id: group.living_room_hue_lights_low_cabinets
  #         brightness: 100
  #         xy_color: [0.459, 0.411]
  #         transition: 1800
  #     - service: light.turn_on
  #       data_template:
  #         entity_id: group.living_room_hue_lights_standing_lamps
  #         brightness: 150
  #         xy_color: [0.459, 0.411]
  #         transition: 1800

  set_hue_scene_transition:
    alias: Set hue mode automatisch
    sequence:
      - service: light.turn_on
        data_template:
          entity_id: group.living_room_hue_lights_low_cabinets
          brightness: "{{ brightness_start_group_1 }}"
          profile: "{{ profile_start_1 }}"
      - service: light.turn_on
        data_template:
          entity_id: group.living_room_hue_lights_standing_lamps
          brightness: "{{ brightness_start_group_2 }}"
          profile: "{{ profile_start_2 }}"
      - delay:
            seconds: 1
      - service: light.turn_on
        data_template:
          entity_id: group.living_room_hue_lights_low_cabinets
          brightness: "{{ brightness_stop_group_1 }}"
          profile: "{{ profile_stop_1 }}"
          transition: "{{ transition|float }}"
      - service: light.turn_on
        data_template:
          entity_id: group.living_room_hue_lights_standing_lamps
          brightness: "{{ brightness_stop_group_2 }}"
          profile: "{{ profile_stop_2 }}"
          transition: "{{ transition|float }}"

  set_hue_scene_auto:
    alias: Set hue mode overgang naar andere scene
    sequence:
      - service: light.turn_on
        data_template:
          entity_id: group.living_room_hue_lights_low_cabinets
          brightness: "{{ brightness_stop_group_1 }}"
          profile: "{{ profile_stop_1 }}"          
          transition: "{{ transition|float }}"
      - service: light.turn_on
        data_template:
          entity_id: group.living_room_hue_lights_standing_lamps
          brightness: "{{ brightness_stop_group_2 }}"
          profile: "{{ profile_stop_2 }}"
          transition: "{{ transition|float }}"

  ##----------------------------------------------
  ## Test scripts >> Remove ASAP after testing 
  ##----------------------------------------------

  ## Added V1.2.0
  ## Test script for setting Hue lamps
  ## used in package_livingroom
  lights_adjust_test:
    alias: licht test aanpassen
    sequence:
      - service: light.turn_on
        data_template:
          entity_id: light.lage_kast_links
          brightness: 1
          xy_color: [0.3698, 0.3723]
      - delay:
          seconds: 1
      - service: light.turn_on
        data_template:
          entity_id: light.lage_kast_links
          brightness: 255
          transition: 10

###############################################################################
##  Timers
###############################################################################

