# Package file for Home Assistant, used for alarms 
# Type: Home Assistant yaml file
# Date: 27-02-2019
# Author: R.Bisschops
#
# Changelog:
# V0.1.0:  First version
# V0.2.0:  Added bed time automation and scripts
# V0.2.1:  Changed bed time script
# V0.2.2:  Changed domoticz entertainment switch to Tradfri

###############################################################################
#                               Homeassistant settings
###############################################################################
  

###############################################################################
#                              Entities
###############################################################################
input_boolean:
## Holiday mode toggle switch, used for setting when on holiday 
## Several automations depend on this
  holiday_mode:
    name: Vakantie mode aan
    icon: mdi:toggle-switch
    initial: off

## Status of lighting in the house used for conditions to see if lighitng is on 
## Several automations depend on this
  # lighting_state:
  #   name: Verlichtings status
  #   icon: mdi:thermometer
  #   initial: off

input_select:
## Electrical toilet heating controlled by Z-Wave Thermostat 
  toilet_heating:
    name: Verwarming toilet
    options:
      - 'Heat'
      - 'Heat Econ'
      - 'Off'  
    initial: 'Off'
    icon: mdi:thermometer

###############################################################################
#                               Groups
###############################################################################


###############################################################################
#                               Automations
###############################################################################
automation:
  - alias: "Bed mode ingeschakeld"
    hide_entity: false
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: 
      - binary_sensor.habridge_bed_time
      to: 'on'
    condition:

    action:
      - service: script.turn_on
        entity_id: script.bedtime

###############################################################################
#                              Templates
###############################################################################


###############################################################################
#                              Scripts
###############################################################################
script:
  bedtime:
    alias: Bedtime script
    sequence:
      - service: homeassistant.turn_off
        entity_id: input_boolean.domo_garden_light
      - service: homeassistant.turn_off
        entity_id: input_boolean.domo_virtual_heating        
      - service: homeassistant.turn_off
        entity_id: switch.tradfri_media_switch
      - service: homeassistant.turn_off
        entity_id: input_boolean.livingroom_lights_status

###############################################################################
#                              Timers
###############################################################################

