# Package file for Home Assistant, used for network monitoring
# Type: Home Assistant yaml file
# Date: 19-01-2019
# Author: R.Bisschops
#
# Changelog:
# V0.1.0:  First version
# V0.2.0:  Added automations for notification
# V1.0.0:  Production version 1.0.0


###############################################################################
#                              Homeassistant settings
###############################################################################

homeassistant:
  customize:
    # Internet statistics 
    sensor.nc_uptime:
      friedly_name: Uptime
    sensor.nc_speedtest_download:
      icon: 'mdi:speedometer'
    sensor.nc_speedtest_upload:
      icon: 'mdi:speedometer'
    sensor.nc_speedtest_ping:
      icon: 'mdi:speedometer'
    # crtical network devices
    sensor.nc_amazonecho:
      icon: 'mdi:microphone'
    sensor.nc_diskstation:
      icon: 'mdi:nas'
    sensor.nc_domoticz_master:
      icon: 'mdi:desktop-tower'
    sensor.nc_domoticz_slave:
      icon: 'mdi:desktop-tower'
    sensor.nc_ha_bridge:
      icon: 'mdi:router-wireless'
    sensor.nc_harmonyhub:
      icon: 'mdi:router-wireless'
    sensor.nc_homeassistant_pi:
      icon: 'mdi:desktop-tower'
    sensor.nc_hue_bridge:
      icon: 'mdi:router-wireless'
    sensor.nc_printer:
      icon: 'mdi:printer'
    sensor.nc_voip:
      icon: 'mdi:phone-voip'
    sensor.nc_xiaomi_bridge:
      icon: 'mdi:router-wireless'
    # other network devices (only when tracked)
    sensor.nc_appletv:
      icon: 'mdi:apple'
    sensor.nc_bosch_dryer:
      icon: 'mdi:tumble-dryer'
    sensor.nc_bosch_washing_machine:
      icon: 'mdi:washing-machine'
    sensor.nc_denon:
      icon: 'mdi:volume-high'     
    sensor.nc_humax:
      icon: 'mdi:satellite-variant'
    sensor.nc_ipad:
      icon: 'mdi:tablet-ipad'  
    sensor.nc_laptop_kim: 
      icon: 'mdi:laptop'
    sensor.nc_laptop_rediscript:
      icon: 'mdi:laptop'  
    sensor.nc_laptop_ralph:
      icon: 'mdi:laptop'
    sensor.nc_lgtelevision:
      icon: 'mdi:television'
    sensor.nc_pc_ralph:
      icon: 'mdi:desktop-tower'
    sensor.nc_popcornhour:
      icon: 'mdi:popcorn'

speedtestdotnet:
  scan_interval:
    hours: 2
  monitored_conditions:
    - ping
    - download
    - upload

###############################################################################
#                              Entities
###############################################################################
sensor:
  - platform: uptime
  - platform: template
    sensors:
    # crtical network devices
      nc_amazonecho:
        friendly_name: 'Amazon echo dot (living room)'
        entity_id:
          - device_tracker.amazonacac5ec30
        value_template: "{{ 'on' if is_state('device_tracker.amazonacac5ec30', 'home') else 'off' }}"
      nc_diskstation:
        friendly_name: 'Diskstation II'
        entity_id:
          - device_tracker.diskstationii
        value_template: "{{ 'on' if is_state('device_tracker.diskstationii', 'home') else 'off' }}"
      nc_domoticz_master:
        friendly_name: 'Domoticz (master)'
        entity_id:
          - device_tracker.raspberrypi
        value_template: "{{ 'on' if is_state('device_tracker.raspberrypi', 'home') else 'off' }}"
      nc_domoticz_slave:
        friendly_name: 'Domoticz (slave)'
        entity_id:
          - device_tracker.raspberrypi_2
        value_template: "{{ 'on' if is_state('device_tracker.raspberrypi_2', 'home') else 'off' }}"
      nc_ha_bridge:
        friendly_name: 'HA Bridge'  
        entity_id:
          - device_tracker.habridge
        value_template: "{{ 'on' if is_state('device_tracker.habridge', 'home') else 'off' }}"  
      nc_harmonyhub:
        friendly_name: 'Harmony Hub'
        entity_id:
          - device_tracker.harmonyhub
        value_template: "{{ 'on' if is_state('device_tracker.harmonyhub', 'home') else 'off' }}"
      nc_homeassistant_pi:
        friendly_name: 'Home Assistant (RPi)'
        entity_id:
          - device_tracker.hassio
        value_template: "{{ 'on' if is_state('device_tracker.hassio', 'home') else 'off' }}"
      nc_hue_bridge:
        friendly_name: 'Philips Hue Bridge'
        entity_id:
          - device_tracker.philipshue
        value_template: "{{ 'on' if is_state('device_tracker.philipshue', 'home') else 'off' }}"
      nc_printer:
        friendly_name: 'HP Laser printer'
        entity_id:
          - device_tracker.npidcd88c          
        value_template: "{{ 'on' if is_state('device_tracker.npidcd88c', 'home') else 'off' }}"    
      nc_voip:
        friendly_name: 'VOIP modem'
        entity_id:
          - device_tracker.n510ippro
        value_template: "{{ 'on' if is_state('device_tracker.n510ippro', 'home') else 'off' }}"
      nc_xiaomi_bridge:
        friendly_name: 'Xiaomi Bridge'
        entity_id:
          - device_tracker.lumigatewayv3_miio78461469
        value_template: "{{ 'on' if is_state('device_tracker.lumigatewayv3_miio78461469', 'home') else 'off' }}"
    # other network devices (only when tracked)
      nc_appletv:
        friendly_name: 'Apple TV'
        entity_id:
          - device_tracker.appletv
        value_template: "{{ 'on' if is_state('device_tracker.appletv', 'home') else 'off' }}"  
      nc_bosch_dryer:
        friendly_name: 'Bosch Wasdroger'
        entity_id:
          - device_tracker.boschwtyh8782nl68a40e22eaca
        value_template: "{{ 'on' if is_state('device_tracker.boschwtyh8782nl68a40e22eaca', 'home') else 'off' }}"
      nc_bosch_washing_machine:
        friendly_name: 'Bosch Wasmachine'
        entity_id:
          - device_tracker.boschwawh2643nl68a40e251509
        value_template: "{{ 'on' if is_state('device_tracker.boschwawh2643nl68a40e251509', 'home') else 'off' }}"
      nc_denon:
        friendly_name: 'Denon AVR3880'
        entity_id:
          - device_tracker.0005cd141d09
        value_template: "{{ 'on' if is_state('device_tracker.0005cd141d09', 'home') else 'off' }}"  
      nc_humax:
        friendly_name: 'Humax i5050'
        entity_id:
          - device_tracker.0003789b9e56
        value_template: "{{ 'on' if is_state('device_tracker.0003789b9e56', 'home') else 'off' }}"  
      nc_ipad:
        friendly_name: 'iPad'
        entity_id:
          - device_tracker.ipadvandiscript
        value_template: "{{ 'on' if is_state('device_tracker.ipadvandiscript', 'home') else 'off' }}"  
      nc_laptop_kim:
        friendly_name: 'Laptop Kim' 
        entity_id:
          - device_tracker.windellu0981qd
        value_template: "{{ 'on' if is_state('device_tracker.windellu0981qd', 'home') else 'off' }}"  
      nc_laptop_ralph:
        friendly_name: 'Laptop Ralph' 
        entity_id:
          - device_tracker.nl1wf6nh2
        value_template: "{{ 'on' if is_state('device_tracker.nl1wf6nh2', 'home') else 'off' }}"  
      nc_laptop_rediscript:
        friendly_name: 'Laptop Rediscript'
        entity_id:
          - device_tracker.desktopqf9r6qv
        value_template: "{{ 'on' if is_state('device_tracker.desktopqf9r6qv', 'home') else 'off' }}"     
      nc_lgtelevision:
        friendly_name: 'LG Televisie'
        entity_id:
          - device_tracker.lgwebostv
        value_template: "{{ 'on' if is_state('device_tracker.lgwebostv', 'home') else 'off' }}"  
      nc_pc_ralph:
        friendly_name: 'PC Ralph'
        entity_id:
          - device_tracker.corei7
        value_template: "{{ 'on' if is_state('device_tracker.corei7', 'home') else 'off' }}"  
      nc_popcornhour:
        friendly_name: 'Popcorn A300' 
        entity_id:
          - device_tracker.a300
        value_template: "{{ 'on' if is_state('device_tracker.a300', 'home') else 'off' }}"  

###############################################################################
#                               Groups
###############################################################################
group:
  all_network_devices:
    name: Netwerk onderdelen
    entities:
      - device_tracker.ipadvandiscript
      - device_tracker.desktopqf9r6qv
      - device_tracker.corei7
      - device_tracker.nl1wf6nh2
      - device_tracker.harmonyhub
      - device_tracker.n510ippro
      - device_tracker.diskstationii
      - device_tracker.npidcd88c
      - device_tracker.raspberrypi
      - device_tracker.habridge
      - device_tracker.raspberrypi_2
      - device_tracker.philipshue
      - device_tracker.amazonacac5ec30
      - device_tracker.hassio
      - device_tracker.lumigatewayv3_miio78461469
      - device_tracker.windellu0981qd
      - device_tracker.747548355361
      - device_tracker.a300
      - device_tracker.appletv
      - device_tracker.lgwebostv
      - device_tracker.0005cd141d09
      - device_tracker.0003789b9e56
      - device_tracker.boschwawh2643nl68a40e251509
      - device_tracker.boschwtyh8782nl68a40e22eaca
  network_stats:
    name: Netwerk statistieken
    entities:
      - sensor.uptime
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.speedtest_ping
  critical_network_parts:
    name: Kritische netwerk componenten
    entities:
      - sensor.nc_diskstation
      - sensor.nc_voip
      - sensor.nc_domoticz_master
      - sensor.nc_domoticz_slave
      - sensor.nc_homeassistant_pi
      - sensor.nc_harmonyhub
      - sensor.nc_hue_bridge
      - sensor.nc_xiaomi_bridge
      - sensor.nc_amazonecho
      - sensor.nc_printer

###############################################################################
#                              Automations
###############################################################################
automation:
  # Sent alert when a critical network device is offline
  - alias: "Netwerk alarm aan"
    hide_entity: false
    initial_state: 'on'
    trigger:
      platform: state
      entity_id:
        - sensor.nc_diskstation
        - sensor.nc_voip
        - sensor.nc_domoticz_master
        - sensor.nc_domoticz_slave
        # - sensor.nc_homeassistant_pi
        - sensor.nc_harmonyhub
        - sensor.nc_hue_bridge
        # - sensor.nc_xiaomi_bridge
        # - sensor.nc_amazonecho
        - sensor.nc_printer
      from: 'on'
      to: 'off'
    condition:

    action:
      - service: script.notify_prowl
        data_template:
          value1: 'Netwerk alarm: '
          value2: '{{ trigger.to_state.attributes.friendly_name }}'
          value3: ' is offline!'
          who: 'ralph'
          prio: 2
  - alias: "Netwerk alarm uit"
    hide_entity: false
    initial_state: 'on'
    trigger:
      platform: state
      entity_id:
        - sensor.nc_diskstation
        - sensor.nc_voip
        - sensor.nc_domoticz_master
        - sensor.nc_domoticz_slave
        # - sensor.nc_homeassistant_pi
        - sensor.nc_harmonyhub
        - sensor.nc_hue_bridge
        # - sensor.nc_xiaomi_bridge
        # - sensor.nc_amazonecho
        - sensor.nc_printer
      from: 'off'
      to: 'on'
    condition:

    action:
      - service: script.notify_prowl
        data_template:
          value1: 'Netwerk alarm: '
          value2: '{{ trigger.to_state.attributes.friendly_name }}'
          value3: ' is online!'
          who: 'ralph'
          prio: -2

###############################################################################
#                              Templates
###############################################################################


###############################################################################
#                              Scripts
###############################################################################


###############################################################################
#                              Timers
###############################################################################

