# Package file for Home Assistant, used for weather  
# Type: Home Assistant yaml file
# Date: 14-01-2019
# Author: R.Bisschops
#
# Changelog:
# V0.1.0:  First version
# V0.2.0:  Added buienradar camera
# V0.3.0:  Removed DarkSky
# V1.0.0:  Production version 1.0
# V1.1.0:  Added tiemframe for buienradar sensor

###############################################################################
#                              Homeassistant settings
###############################################################################


###############################################################################
#                              Entities
###############################################################################

camera:
  ## CAMERA USED FOR BUIENRADAR
  - platform: generic
    name: buienradar
    still_image_url: 'https://api.buienradar.nl/image/1.0/RadarMapNL?w=256h=256'

weather:
  ## WEATHER PLATFORM
  - platform: buienradar  

sensor:
  # BUIENRADAR
  - platform: buienradar
    timeframe: 10
    monitored_conditions:
      - stationname
      - conditioncode
      - condition
      - conditiondetailed
      - conditionexact    
      - symbol
      - humidity
      - temperature
      - groundtemperature
      - windspeed
      - windforce
      - winddirection
      - windazimuth
      - pressure
      - visibility
      - windgust
      - precipitation
      - irradiance
      - precipitation_forecast_average
      - precipitation_forecast_total
      # Forecast
      - rainchance_1d
      - rainchance_2d
      - rainchance_3d
      - rainchance_4d
      - rainchance_5d
      - sunchance_1d
      - sunchance_2d
      - sunchance_3d
      - sunchance_4d
      - sunchance_5d
      - symbol_1d
      - symbol_2d
      - symbol_3d
      - symbol_4d
      - symbol_5d

###############################################################################
#                              Templates
###############################################################################


###############################################################################
#                               Groups
###############################################################################


###############################################################################
#                               Automations
###############################################################################


###############################################################################
#                              Scripts
###############################################################################


###############################################################################
#                              Timers
###############################################################################
