# Package file for Home Assistant, used for alarms 
# Type: Home Assistant yaml file
# Date: 22-03-2019
# Author: R.Bisschops
#
# Changelog:
# V0.1.0:  First version
# V0.2.0:  Added bed time automation and scripts
# V0.2.1:  Changed bed time script
# V0.2.2:  Changed domoticz entertainment switch to Tradfri
# V0.3.0:  Moved input select toliet heating to package_toilet
# V0.3.1:  Added Tradfri testswitch
# V0.3.2:  Minor code clean
# V0.4.0:  Removed Tradfri testswitch
# V0.4.1:  Added condition recording mode in bedtime script 
# V0.5.0:  Added test services in script for toilet heating
# V0.5.1:  Added toilet heating settings to the the bed time script 
# V0.6.0:  Added template sensors for waste bin schedular 

###############################################################################
#                               Homeassistant settings
###############################################################################
  

###############################################################################
#                              Entities
###############################################################################
input_boolean:
## Holiday mode toggle switch, used for setting when on holiday 
## Several automations depend on this
  holiday_mode:
    name: Vakantie mode aan
    icon: mdi:toggle-switch
    initial: off

## Definition of workdays with the workday sensor
## Used in several automations
binary_sensor:
  - platform: workday
    country: NL
    workdays: [mon, tue, wed, thu, fri, sat]
    excludes: [sun]

  - platform: template
    sensors:
      gft:
        friendly_name: GFT
        value_template: >-
          {% if is_state('calendar.afval_kalender', 'on') %}
            {% if state_attr('calendar.afval_kalender', 'message') == 'GFT' %}
              true
            {% elif state_attr('calendar.afval_kalender', 'message') == 'GFT + PMD' %}
              true
            {% else %}
              false
            {% endif %}
          {% else %}
            false
          {% endif %}
        entity_picture_template: >-
          {{ '/local/custom_icons/gft48_' ~ states.binary_sensor.gft.state ~ '.png' }}

  - platform: template
    sensors:
      pmd:
        friendly_name: PMD
        value_template: >-
          {% if is_state('calendar.afval_kalender', 'on') %}
            {% if state_attr('calendar.afval_kalender', 'message') == 'PMD' %}
              true
            {% elif state_attr('calendar.afval_kalender', 'message') == 'GFT + PMD' %}
              true
            {% else %}
              false
            {% endif %}
          {% else %}
            false
          {% endif %}
        entity_picture_template: >-
          {{ '/local/custom_icons/pmd48_' ~ states.binary_sensor.pmd.state ~ '.png' }}

###############################################################################
#                               Groups
###############################################################################


###############################################################################
#                               Automations
###############################################################################
automation:
  - alias: "Bed mode ingeschakeld"
    hide_entity: false
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: 
      - binary_sensor.habridge_bed_time
      to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.bedtime

###############################################################################
#                              Templates
###############################################################################


###############################################################################
#                              Scripts
###############################################################################
script:
  bedtime:
    alias: Bedtime script
    sequence:
      - service: homeassistant.turn_off
        entity_id: input_boolean.domo_garden_light
      - service: homeassistant.turn_off
        entity_id: input_boolean.domo_virtual_heating        
      - service: homeassistant.turn_off
        entity_id: input_boolean.livingroom_lights_status
      ## Service added for climate settings toilet  
      - service: script.set_toilet_heating_mode
        data_template:
          mode: 'Energy Heat'
      - condition: state
        entity_id: input_boolean.recording_mode
        state: 'off'
      - service: homeassistant.turn_off
        entity_id: switch.tradfri_media_switch

###############################################################################
#                              Timers
###############################################################################

