## Package file for Home Assistant, used for the Livingroom
## Type: Home Assistant yaml file
## Date: 10-03-2019
## Author: R.Bisschops
##
## Changelog:
## V0.1.0:  First version
## V0.2.0:  Major updates
## V0.3.0:  Added various switches for entities based on HA Bridge control
## V0.3.1:  Bugfix formatting entities 
## V0.3.2:  Added new sensors/switches
## V0.3.3:  Changed ha bridge to domo automations to one script - experimental
## V0.4.0:  Removed HA-Bridge automation for gardenlights (moved to package_garden)
## V0.4.1:  Removed media modes for lighting
## v0.4.2:  Moved Domoticz automations and scripts to domo2hass package
## V0.5.0:  Added Treadfri switch for kitchen high cabinets
## V0.5.1:  Restored CoCo kitchen high cabinets switch
## V0.5.2:  Cleanup code
## V0.6.0:  Moved in automations from package_presence
## V0.7.0:  Added livingroom lights at sunset
## V0.8.0:  Moved automations to package_hallway and packag_storage
## V0.9.0:  Added christmas tree to automations.
##          Changed script livingroom lights off. Introduced timer.
## V0.10.0: Changed the offset for sun conditions in automation
##          Woonkamer verlichting aan bij thuiskomst to -01:00:00
## V0.11.0: Added test script for hue light control light
## V0.12.0: Changed automation sunset to start script for slow increase of brightness (package_hue script)
##          Added time for kitchen light on at sunset

###############################################################################
##  Homeassistant settings
###############################################################################
homeassistant:
  customize:
    ## ZigBeee2MQTT Switches
    switch.tradfri_media_switch:
      friendly_name: Entertainment
    switch.tradfri_high_cabinets_switch:
      friendly_name: Verlichting hoge kasten (ZigBee)
    ## Scripts        
    script.livingroom_lights_on:
      icon: mdi:lightbulb
    script.livingroom_lights_off:
      icon: mdi:lightbulb
    script.livingroom_lights_adjust:
      icon: mdi:lightbulb

# logger:
#   default: info
#   logs:
#     homeassistant.components.script: debug

###############################################################################
##  Entities
###############################################################################
input_select:
 ## Mode selector for the lights in the livingroom
 ## used for the modes the light can be set in from media center 
  livingroom_lights_mode:
    name: Verlichtsmode Woonkamer
    options:
      - Normaal
      - Video
    initial: Normaal
    icon: mdi:lightbulb

input_boolean:
  ## Status of lighting in the livingroom used to see if lighitng is on 
  ## several automations depend on this
  livingroom_lights_status:
    name: Verlichting woonkamer

switch:
  ## Switch for high cabinets (Tradfri via Zigbee2MQTT)
  - platform: "mqtt"
    name: tradfri_high_cabinets_switch
    state_topic: "zigbee2mqtt/tradfri_high_cabinets_switch"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_off: "OFF"
    payload_on: "ON"
    value_template: "{{ value_json.state }}"
    command_topic: "zigbee2mqtt/tradfri_high_cabinets_switch/set"

sensor:
  ## Switch for high cabinets, sensor (Tradfri via Zigbee2MQTT)
  - platform: "mqtt"
    name: tradfri_high_cabinets_switch
    state_topic: "zigbee2mqtt/tradfri_high_cabinets_switch"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "-"
    value_template: "{{ value_json.linkquality }}"   

###############################################################################
##  Groups
###############################################################################


###############################################################################
##  Automations
###############################################################################
automation:
  ## Switch on livingroom lights from HA-Bridge
  - alias: "Verlichting woonkamer aan (HA Bridge)"
    hide_entity: false
    initial_state: 'on'
    trigger:
      platform: state
      entity_id:
        - binary_sensor.habridge_livingroom_lights_on
      to: 'on'
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.livingroom_lights_status

  ## Switch off livingroom lights from HA-Bridge
  - alias: "Verlichting woonkamer uit (HA Bridge)"
    hide_entity: false
    initial_state: 'on'
    trigger:
      platform: state
      entity_id:
        - binary_sensor.habridge_livingroom_lights_off
      to: 'on'
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.livingroom_lights_status

  ## Switch livingroom lights on and off
  - alias: "Verlichting woonkamer"
    hide_entity: false
    initial_state: 'on'
    trigger:
      platform: state
      entity_id:
        - input_boolean.livingroom_lights_status
    action:
      - service_template: >-
          {% if is_state('input_boolean.livingroom_lights_status', 'on') %}
            script.livingroom_lights_on
          {% elif is_state('input_boolean.livingroom_lights_status', 'off') %}
            script.livingroom_lights_off
          {% endif%}

  ## Switch on livingroom lights when someone arrives home
  - alias: "Woonkamer verlichting aan bij thuiskomst"
    hide_entity: false
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: 
          - binary_sensor.neo_coolcam_front_door
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: sun
          after: sunset
          after_offset: '-01:00:00'
        - condition: state
          entity_id: input_boolean.livingroom_lights_status
          state: 'off'
        - condition: or
          conditions:
            - condition: state
              entity_id: input_select.ralph_status_dropdown
              state: 'Just Arrived'
            - condition: state
              entity_id: input_select.anneke_status_dropdown
              state: 'Just Arrived'
            - condition: state
              entity_id: input_select.kimberly_status_dropdown
              state: 'Just Arrived'
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.livingroom_lights_status
      - service: homeassistant.turn_on
        entity_id: 
          - input_boolean.domo_christmastree

  ## Added V0.7.0, Updated V0.11.0
  ## Switch on livingroom lights at sunset
  - alias: "Woonkamer verlichting aan bij zonsondergang"
    hide_entity: false
    initial_state: 'on'
    trigger:
      platform: sun
      event: sunset
      offset: '-01:00:00'
    condition:
      condition: and
      conditions: 
        - condition: state
          entity_id: binary_sensor.people_home
          state: 'on'
        - condition: state
          entity_id: input_boolean.holiday_mode
          state: 'off'
    action:
      - service: script.turn_on
        entity_id: script.hue_sunset_mode
      - service: timer.start
        data_template:
          entity_id: timer.kitchencabinets_on
          duration: '01:00:00'
      - service: timer.start
        data_template:
          entity_id: timer.christmastree_on
          duration: '01:00:00'

  ## Switch bar lights on an off from HA-Bridge
  - alias: "Bar lampen - voice"
    hide_entity: false
    initial_state: 'on'
    trigger:
      platform: state
      entity_id:
        - binary_sensor.habridge_bar_light
    action:
      - service_template: >-
          {% if is_state('binary_sensor.habridge_bar_light', 'on') %}
            homeassistant.turn_on
          {% elif is_state('binary_sensor.habridge_bar_light', 'off') %}
            homeassistant.turn_off
          {% endif%}
        entity_id: input_boolean.domo_bar_light

  ## Switch Christmas tree on and off from HA-Bridge
  - alias: "Kerstboom - voice"
    hide_entity: false
    initial_state: 'on'
    trigger:
      platform: state
      entity_id:
        - binary_sensor.habridge_christmastree
    action:
      - service_template: >-
          {% if is_state('binary_sensor.habridge_christmastree', 'on') %}
            homeassistant.turn_on
          {% elif is_state('binary_sensor.habridge_christmastree', 'off') %}
            homeassistant.turn_off
          {% endif%}
        entity_id: input_boolean.domo_christmastree

  ## Added V0.9.0
  ## Switch off kitchen cabinets light based on timer
  - alias: "Hoge kasten keuken uit xx minuten na trigger"
    hide_entity: false
    initial_state: 'on'
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.kitchencabinets
    condition:
    action:
    - service: homeassistant.turn_off
      entity_id: 
        - input_boolean.domo_kitchen_cabinets
        # - switch.tradfri_high_cabinets_switch

  ## Added V0.11.0
  ## Switch on kitchen cabinets light based on timer
  - alias: "Hoge kasten keuken aan xx minuten na trigger"
    hide_entity: false
    initial_state: 'on'
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.kitchencabinets_on
    condition:
    action:
    - service: homeassistant.turn_on
      entity_id: 
        - input_boolean.domo_kitchen_cabinets
        # - switch.tradfri_high_cabinets_switch

  ## Added V0.11.0
  ## Switch on christmas tree based on timer
  - alias: "Cristmas tree aan xx minuten na trigger"
    hide_entity: false
    initial_state: 'on'
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.christmastree_on
    condition:
    action:
    - service: homeassistant.turn_on
      entity_id: 
        - input_boolean.domo_christmastree

  ## Adeed in V0.11.0
  ## Test automation for testing direct color control on a hue lamp >> remove asap
  - alias: Test hue color and transitions on
    hide_entity: false
    initial_state: 'on'
    trigger:
      platform: state
      entity_id:
        - input_boolean.hallway_livingroom_door
      to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.hue_video_mode

  ## Adeed in V0.11.0
  ## Test automation for testing direct color control on a hue lamp >> remove asap
  - alias: Test hue color and transitions off
    hide_entity: false
    initial_state: 'on'
    trigger:
      platform: state
      entity_id:
        - input_boolean.hallway_livingroom_door
      to: 'off'
    action:
      - service: script.turn_on
        entity_id: script.hue_sunset_mode

###############################################################################
##  Scripts
###############################################################################
script:
  livingroom_lights_on:
    alias: Woonkamer licht aan script
    sequence:
      - service: homeassistant.turn_on
        entity_id: 
          - input_boolean.domo_kitchen_cabinets
      # - service: homeassistant.turn_on
      #   entity_id: 
      #     - switch.tradfri_high_cabinets_switch
      - service: input_select.select_option
        data_template:
          entity_id: input_select.hue_scenes
          option: >-
            {% if is_state('input_select.livingroom_lights_mode', 'Normaal') %}
            Verlichting aan
            {% elif is_state('input_select.livingroom_lights_mode', 'Video') %}
            TV mode
            {% endif %}          
      - service: script.set_hue_scene
        data_template:
          group: 'Woonkamer'
          name: '{{ states.input_select.hue_scenes.state }}'
      - service: homeassistant.turn_on
        entity_id: input_boolean.domo_christmastree

  livingroom_lights_off:
    alias: Woonkamer licht uit script
    sequence:
      - service: timer.start
        data:
          entity_id: timer.kitchencabinets
      - service: homeassistant.turn_off
        entity_id: 
          - light.woonkamer
      - service: homeassistant.turn_off
        entity_id:
          - input_boolean.domo_christmastree

  livingroom_lights_adjust:
    alias: woonkamer licht aanpassen script
    sequence:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.hue_scenes
          option: >-
            {% if is_state('input_select.livingroom_lights_mode', 'Normaal') %}
            Verlichting aan
            {% elif is_state('input_select.livingroom_lights_mode', 'Video') %}
            TV mode
            {% endif %}          
      - service: script.set_hue_scene
        data_template:
          group: 'Woonkamer'
          name: '{{ states.input_select.hue_scenes.state }}'

###############################################################################
##  Timers
###############################################################################
timer:
  kitchencabinets:
    duration: '00:01:00'
  kitchencabinets_on:
  christmastree_on:  
