# Package file for Home Assistant, used for alarms 
# Type: Home Assistant yaml file
# Date: 22-03-2019
# Author: R.Bisschops
#
# Changelog:
# V0.1.0:  First version
# V0.2.0:  Added bed time automation and scripts
# V0.2.1:  Changed bed time script
# V0.2.2:  Changed domoticz entertainment switch to Tradfri
# V0.3.0:  Moved input select toliet heating to package_toilet
# V0.3.1:  Added Tradfri testswitch

###############################################################################
#                               Homeassistant settings
###############################################################################
  

###############################################################################
#                              Entities
###############################################################################
input_boolean:
## Holiday mode toggle switch, used for setting when on holiday 
## Several automations depend on this
  holiday_mode:
    name: Vakantie mode aan
    icon: mdi:toggle-switch
    initial: off

## Definition of workdays with the workday sensor
## Used in several automations
binary_sensor:
  - platform: workday
    country: NL
    workdays: [mon, tue, wed, thu, fri]
    excludes: [sat, sun]

switch:
  # Switch for test operations (Tradfri via Zigbee2MQTT)
  - platform: "mqtt"
    name: tradfri_test_switch
    state_topic: "zigbee2mqtt/tradfri_test_switch"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_off: "OFF"
    payload_on: "ON"
    value_template: "{{ value_json.state }}"
    command_topic: "zigbee2mqtt/tradfri_test_switch/set"
sensor:
  # Switch for test operations, sensor (Tradfri via Zigbee2MQTT)
  - platform: "mqtt"
    name: tradfri_test_switch
    state_topic: "zigbee2mqtt/tradfri_test_switch"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "-"
    value_template: "{{ value_json.linkquality }}"       

###############################################################################
#                               Groups
###############################################################################


###############################################################################
#                               Automations
###############################################################################
automation:
  - alias: "Bed mode ingeschakeld"
    hide_entity: false
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: 
      - binary_sensor.habridge_bed_time
      to: 'on'
    condition:

    action:
      - service: script.turn_on
        entity_id: script.bedtime

###############################################################################
#                              Templates
###############################################################################


###############################################################################
#                              Scripts
###############################################################################
script:
  bedtime:
    alias: Bedtime script
    sequence:
      - service: homeassistant.turn_off
        entity_id: input_boolean.domo_garden_light
      - service: homeassistant.turn_off
        entity_id: input_boolean.domo_virtual_heating        
      - service: homeassistant.turn_off
        entity_id: switch.tradfri_media_switch
      - service: homeassistant.turn_off
        entity_id: input_boolean.livingroom_lights_status

###############################################################################
#                              Timers
###############################################################################

