# Package file for Home Assistant, used for presence  
# Type: Home Assistant yaml file
# Date: 14-01-2019
# Author: R.Bisschops
#
# Changelog:
# V0.1.0:  First version
# V1.0.0:  Production version 1.0.0
# V1.1.0:  Added hallway light based on trigger frontdoor sensor 

###############################################################################
#                              Homeassistant settings
###############################################################################
homeassistant:
  customize:
    ### Timers
    timer.porchlight:
      friendly_name: Buitenlamp
    timer.hallwaylight:
      friendly_name: Halletje  

## Settings for owntracks
owntracks:
  max_gps_accuracy: 200

###############################################################################
#                              Entities
###############################################################################
binary_sensor:
  - platform: template
    sensors:
      people_home:
        friendly_name: Iemand thuis
        value_template: >-
          {{ is_state('device_tracker.owntracks_anneke_s7', 'home')
            or is_state('device_tracker.owntracks_kim_s7', 'home')
            or is_state('device_tracker.owntracks_ralph_iphone7', 'home') }}
        entity_picture_template: >-
          {{ '/local/custom_icons/people48_' ~ states.binary_sensor.people_home.state ~ '.png' }}    

###############################################################################
#                               Groups
###############################################################################
group:
  presence_devices:
    name: Aanwezigheid (Netwerk)
    entities:
      - device_tracker.anneke_s7
      - device_tracker.kimberly_s7
      - device_tracker.ralph_iphone7
  presence_geofence:
    name: Aanwezigheid (Geofence)
    entities:
      - device_tracker.owntracks_anneke_s7
      - device_tracker.owntracks_kimberly_s7
      - device_tracker.owntracks_ralph_iphone7
  presence_states:
    name: Aanwezigheid
    entities:
      - binary_sensor.people_home
  presence_timers:
    name: Aanwezigheid timers
    entities:
      - timer.porchlight
      - timer.hallwaylight

###############################################################################
#                               Automations
###############################################################################
automation:
  ## Test if everybody is away and perform actions
  - alias: "Iedereen is weg"
    hide_entity: false
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: group.presence_geofence
      to: 'not_home'
    condition:

    action:
      - service: script.notify_prowl
        data_template:
          value1: 'Afwezigheidsmelding: '
          value2: ''
          value3: 'Iedereen is weg'
          who: 'ralph'
          prio: -2

  ## Test if anybody comes home and perform actions
  - alias: "Er komt iemand thuis"
    hide_entity: false
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: device_tracker.owntracks_anneke_s7, device_tracker.owntracks_kimberly_s7, device_tracker.owntracks_ralph_iphone7
      from: 'not_home'
      to: 'home'
    condition:

    action:
      - service: script.notify_prowl
        data_template:
          value1: 'Aanwezigheidsmelding: '
          value2: '{{ trigger.to_state.attributes.friendly_name }}'
          value3: ' komt thuis'
          who: 'ralph'
          prio: -2

  ## Switch on porch light when someone arrives home
  - alias: "Buitenlamp bij thuiskomst"
    hide_entity: false
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: device_tracker.owntracks_anneke_s7, device_tracker.owntracks_kimberly_s7, device_tracker.owntracks_ralph_iphone7
      from: 'not_home'
      to: 'home'
    condition:  
      condition: or
      conditions:     
        - condition: sun
          after: sunset
        - condition: sun
          before: sunrise
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.domo_porch_light
      - service: timer.start
        data:
          entity_id: timer.porchlight

  ## Switch on hallway light when someone arrives home
  - alias: "Halletje aan bij thuiskomst"
    hide_entity: false
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: 
          - binary_sensor.neo_coolcam_front_door
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.domo_porch_light
          state: 'on'
        - condition: sun
          after: sunset
          after_offset: "00:15:00"
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.domo_hallway_light
      - service: timer.start
        data:
          entity_id: timer.hallwaylight     

  ## Switch off porchlight based on timer
  - alias: "Buitenlamp uit xx minuten na trigger"
    hide_entity: false
    initial_state: 'on'
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.porchlight
    condition:

    action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.domo_porch_light

   ## Switch off hallway light based on timer
  - alias: "Halletje uit xx minuten na trigger"
    hide_entity: false
    initial_state: 'on'
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.hallwaylight
    condition:

    action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.domo_hallway_light


###############################################################################
#                              Templates
###############################################################################


###############################################################################
#                              Scripts
###############################################################################


###############################################################################
#                              Timers
###############################################################################
timer:
  porchlight:
    duration: '00:10:00'
  hallwaylight:
    duration: '00:02:00'
